# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20181006_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='anonymous', max_length=50),
            preserve_default=False,
        ),
    ]
