# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
