# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_userprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='edit_email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
