# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_userprofile_edit_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='edit_email',
            new_name='email',
        ),
    ]
