# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20181006_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
