# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_userprofile_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_photo',
            new_name='change_profile_photo',
        ),
    ]
