# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 09:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0015_auto_20181008_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
