# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 12:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_auto_20181008_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photolikes',
            name='liked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photolikes',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='photos.Photo'),
        ),
    ]
